version: '2'
services:
  av:
    build: ./av
    privileged: true
    expose:
      - "80"
    volumes:
      - shared-data:/data
#  sensors:
#    build: ./sensors
#    privileged: true
#    volumes:
#      - shared-data:/data
  monitoring:
    build: ./monitoring
    expose:
      - "9090"
    volumes:
      - shared-data:/data
volumes:
  shared-data:
