version: '2'
services:
  av:
    build: ./av
    privileged: true
    volumes:
      - shared-data:/data

  sensors:
    build: ./sensors
    privileged: true
    volumes:
      - shared-data:/data

  node-exporter:
    image: dynamicdevices/balenablock-node-exporter@sha256:9c03ad3c3c7b6201c0f5a644d5d7023e8ecb42767c55945082807e16e4eb60de
    restart: always
    privileged: false
    ports:
      - '80:9100'

volumes:
  shared-data:
