version: '2'
services:
  av:
    build: ./av
    privileged: true
    expose:
      - "80"
    volumes:
      - /data:/data
  sensors:
    build: ./sensors
    privileged: true
    volumes:
      - /data:/data
